build: false
platform: 'x86'
clone_folder: C:\projects\cli-menu
branches:
  except:
    - gh-pages

init:
    - SET COMPOSER_NO_INTERACTION=1

install:
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\cli-menu
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-progress

test_script:
  - ps: cd C:\projects\cli-menu
  - ps: gl
  - vendor\bin\phpunit.bat
